### ISSUE TITLE
OverflowError in windows platform

### ISSUE THREAD

**Issue by jason-xuan** [AsafManela/HurdleDMR.jl#13] opened 2020-02-21 03:17 UTC
In julia version 1.3, windows platform, there is an Error while running test case:
```
PositivePoisson: Error During Test at C:\Users\jason\.julia\dev\HurdleDMR\test\positive_poisson.jl:1
  Got exception outside of a @test
  OverflowError: 22 is too large to look up in the table; consider using `factorial(big(22))` instead
```

**Comment by AsafManela** [comment] 2020-12-14 20:00
Cannot reproduce this testing issue in julia 1.5, so closing for now.

**Closed by AsafManela** 2020-12-14 20:00 UTC
